### ISSUE TITLE
DeprecationWarning: Chunk.modules is deprecated.

### ISSUE THREAD

**Issue by c0defre4k** [FullHuman/purgecss-webpack-plugin#1]
In Webpack >= 3 this warning is thrown:
```
DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.
```

In this case `search.js`'s files method should use the `Chunk.mapModules` instead of `Object.keys` to get the same result.

**Comment by Ffloriel** [comment]
Thank you very much @c0defre4k for the information, I updated the code to replace the deprecated property.
The warning should not appear anymore in v0.10.1.
