### ISSUE TITLE
purgecss-webpack-plugin 1.0.0

### ISSUE THREAD

**Issue by zhenbinjing** [FullHuman/purgecss-webpack-plugin#20]
I suggest replacing extract-text-webpack-plugin with mini-css-extract-plugin

**Comment by jsnanigans** [comment]
Hey, that's a great idea, ill add it to the webpack-4 branch when I get a moment and when webpack 4 is more commonly used Ill replace the master

**Comment by jsnanigans** [comment]
I will close this issue for now, when mini-css-extract-plugin supports HMR I will replace extract-text-webpack-plugin,
thank you for the suggestion
