### ISSUE TITLE
nuxt.js (ssr) - purgecss inline

### ISSUE THREAD

**Issue by ms-webdev** [FullHuman/purgecss-webpack-plugin#21]
Hi,
do you have a solution to embed the purgecss result to a nuxt-ssr-app, **inlined**?

Your plugin only works when I set this nuxt build option to:

`extractCSS: true`

when I set this option to 'false' then nuxt will build the whole css to my production app and not the purgecss result.

You find the build snippet here:

[github.com/ms-webdev/nuxt-express-quick-start](https://github.com/ms-webdev/nuxt-express-quick-start/blob/master/nuxt.config.js#L36)

I hope you can help me

**Comment by jsnanigans** [comment]
Hi, sorry I didn't get to you earlier.
at the moment purgecss-webpack-plugin only works with `extractCSS: true` because it needs those css files

**Comment by alexjoverm** [comment]
Is there any way to make it work when using inline CSS? Still having this issue in a quite large e-commerce that we're building in Nuxt.

Poking @Atinux and @alexchopin for posible feedback on this.

**Comment by jsnanigans** [comment]
@alexjoverm you could use the postcss-purgecss instead, you will have to add the postcss loader to your webpack config and then add purgecss as a plugin
