### ISSUE TITLE
Allow .css files in paths

### ISSUE THREAD

**Issue by sebastiandedeyne** [FullHuman/purgecss-webpack-plugin#3]
Due to this line it's currently impossible to provide .css files to extract selectors from.

https://github.com/FullHuman/purgecss-webpack-plugin/blob/6a981502497969c21f1ecefae16fee0554c03502/src/index.js#L38

I want to pass my hand-written css files to an extractor so that css never gets purged, I only want to purge unused vendor/framework css.

Would it be possible to allow css files in paths?

**Comment by Ffloriel** [comment]
I'm not sure it would be the right way to do it.
I think you can separate your vendor files and your own with webpack.

What you want to do would have the same result as the populating the `whitelist` option with the css. [whitelist docs](https://www.purgecss.com/whitelisting.html)
 The idea would be to do something like this:

```js
const Purgecss = require('purgecss')
const purgecss = new Purgecss({
    css: [],
    content: []
}
```
and use the purgecss method to get the selector
```js
/**
     * Extract the selectors present in the files using a purgecss extractor
     * @param {array} files Array of files path or glob pattern
     * @param {array} extractors Array of extractors
     */
    extractFileSelector(files: Array<string>, extractors?: Array<ExtractorsObj>): Set<string> {
```

```js
const myCssSelectors = purgecss.extractFileSelector(['mycss/*.css'])
// return a set of selectors
```

**Comment by Ffloriel** [comment]
I think it's better if the plugin provides a way to select css files that should not be purged. I will try to add this option.

**Comment by sebastiandedeyne** [comment]
> I think it's better if the plugin provides a way to select css files that should not be purged. I will try to add this option.

This doesn't work in my case since app css and vendor css end up in the same file, and I only need to purge the vendor stuff...

**Comment by jsnanigans** [comment]
Hi,
This plugin purges the files before they are written to disk, If you would be able to select css files that should not be purged like @Ffloriel said then you can only purge your vendor.css and the app.css will not be touched. 

It all depends on how you concat. the two into one file.
If you are using some webpack plugin then you should be sure that the order of the plugins is as follows: purge, concat, extract-text.
If you are doing it post-build then it does not really matter

**Comment by sebastiandedeyne** [comment]
On second thought, I think being able to ignore an entry for purging would be good enough for me

**Comment by qodesmith** [comment]
@Ffloriel Trying your suggestion above, but keep getting `Error: No content provided.`. Here's the code I'm using:

```
const Purgecss = require('purgecss')
const purgecss = new Purgecss({
  css: [],
  content: []
})
const selectors = purgecss.extractFileSelector(['node_modules/typer-js/typer.css'])
console.log('SELECTORS:', selectors)
```

Was hoping to see what the value of `selectors` was. Didn't know that there was a way to extract a list of selectors from a file. This will help me because right now I'm manually passing in a `whiteList` array that I've had to create myself. This isn't a big problem at the minute since there's only like 7 selectors in that list. But I could imagine if I was dealing with multiple files and a ton of selectors I wanted whitelisted, that `extractFileSelector` would come in handy. Just can't get it to work.

**Comment by qodesmith** [comment]
@sebastiandedeyne  As to my comments above (and to your original needs), I ended up creating a [tool](https://github.com/qodesmith/purgecss-whitelister) that does exactly this - [Purgecss Whitelister](https://github.com/qodesmith/purgecss-whitelister). You pass the thing a string of a filename (or an array of strings... or an array of globy strings) and it spits out a list containing all the selectors in that CSS file which Purgecss can consume.

An example that I'm currently using:
```javascript
const whitelister = require('purgecss-whitelister');
const PurgecssPlugin = require('purgecss-webpack-plugin');
const glob = require('glob-all')
const { resolve } = require('path');

const whitelist = whitelister(resolve(resolve(), 'node_modules/typer-js/typer.css'));

const webpackConfig = {

  // ...a whole buncha stuffs up here...

  plugins: [
    new PurgecssPlugin({
      keyframes: false, // https://goo.gl/bACbDW
      styleExtensions: ['.css'],
      paths: glob.sync([
        resolve(resolve(), 'src/**/*.js'),
        resolve(resolve(), 'src/index.ejs')
      ]),

      // `whiltelist` needed to ensure Typer classes stay in the bundle.
      whitelist: whitelist,
      extractors: [
        {
          // https://goo.gl/hr6mdb
          extractor: class AvoidBacktickIssue {
            static extract(content) {
              return content.match(/[A-Za-z0-9_-]+/g) || [];
            }
          },
          extensions: ['js'] // file extensions
        }
      ]
    }),

    // ...probably more plugins & things...
  ]
}
```

Hope that helps!
