### ISSUE TITLE
Declare Webpack as a peer dependency?

### ISSUE THREAD

**Issue by javiereguiluz** [FullHuman/purgecss-webpack-plugin#30]
First, thanks for creating and maintaining this project!

I'm using Webpack 3 and I installed this plugin as `yarn add --dev purgecss-webpack-plugin` ... which installed the Webpack 4 compatible plugin and resulted in a hard-to-debug issue (see https://github.com/symfony/webpack-encore/issues/330). I know that your installation instructions show different commands for Webpack 3 and 4 ... but I missed that.

The people that helped me solve this problem wondered why this plugin declares Webpack as a dependency instead of a [peer dependency](https://nodejs.org/en/blog/npm/peer-dependencies/) so I created this issue to ask the same in case it helps this project. 

Thanks!

**Comment by jsnanigans** [comment]
Thanks for bringing this up, this is embarrassing but I actually didn't know about peer dependencies :sweat_smile:. I will change this as soon as possible!
