### ISSUE TITLE
Error: EISDIR: illegal operation on a directory

### ISSUE THREAD

**Issue by firestar300** [FullHuman/purgecss-webpack-plugin#39]
Hello, I try to install purgecss-webpack-plugin on my stack but I get the following error :

```
/Volumes/APPLE SD Card/Projets/beapi/beapi-frontend-framework/themes/beapi-frontend-framework/node_modules/purgecss-webpack-plugin/node_modules/purgecss/lib/purgecss.js:674
                        throw _iteratorError5;
                        ^

Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:690:18)
    at tryReadSync (fs.js:554:20)
    at Object.fs.readFileSync (fs.js:597:19)
    at Purgecss.extractFileSelector 
```

You can reproduce the issue by cloning the repo : https://github.com/BeAPI/beapi-frontend-framework/tree/experiment/purgecss

```
$ npm install
$ npm run build:test
```

Version of purgecss-webpack-plugin : 1.2.0

**Comment by jsnanigans** [comment]
Hey, did you manage to fix the issue? I can't see purgecss-webpack-plugin in your repo

**Comment by firestar300** [comment]
Hello @jsnanigans ! Nope, I didn't find a way to fix this issue. What do you mean by "I can't see purgecss-webpack-plugin in your repo" ?  I installed the node package as devDependency : https://github.com/BeAPI/beapi-frontend-framework/blob/experiment/purgecss/package.json#L66

**Comment by sbdchd** [comment]
You likely need to pass `{noDir: true}` as an option to [`glob.sync()`](https://github.com/isaacs/node-glob#options) as `glob.sync` is matching a dir which the plugin can't operate on.

```js
new PurgecssPlugin({
  paths: glob.sync(`${paths.appSrc}/**/*`)
}),
// becomes
new PurgecssPlugin({
  paths: glob.sync(`${paths.appSrc}/**/*`, { nodir: true })
}),
```

**Comment by biggamejames** [comment]
I ran into this issue as well. Passing nodir worked.
