### ISSUE TITLE
npm WARN purgecss-webpack-plugin@1.2.0 requires a peer of webpack@^4.11.1 but none is installed. You must install peer dependencies yourself.

### ISSUE THREAD

**Issue by sinanerdem** [FullHuman/purgecss-webpack-plugin#40]
**Describe the bug**
I believe this plugin supports webpack 3 which I am using (webpack 3.12.0)
Whenever I install a new npm module, there are two warnings:

npm WARN purgecss-webpack-plugin@1.2.0 requires a peer of webpack@^4.11.1 but none is installed. You must install peer dependencies yourself.
npm WARN purgecss-webpack-plugin@1.2.0 requires a peer of webpack-cli@^3.0.2 but none is installed. You must install peer dependencies yourself.

**To Reproduce**

Install any other npm module.

**Expected behavior**
Nothing

**Comment by jsnanigans** [comment]
Thanks for reporting this, the webpack warning is easily fixed, however i'm not sure that you can define a optional peer-dependency - webpack-cli.

but otherwise its working for you right?

Ill try to fix these warnings when I have some time.

**Comment by sinanerdem** [comment]
Thank you. It doesn't effect the operation of the plugin. It was just a bit confusing.

**Comment by sebastiandedeyne** [comment]
Is Webpack 3 still supported? Doesn't the peerDependency need to be changed to something like `^3 || ^4`?

**Comment by jsnanigans** [comment]
Thanks for the suggestion, I changed the webpack peerDependency however I don't think we can get rid of the warning for `webpack-cli`

**Comment by calebeby** [comment]
@jsnanigans Why does this package even have a peerDependency on `webpack-cli` at all? This package can work with the webpack api without the CLI, right? Can I send a PR to remove the `peerDependency` on `webpack-cli`?

**Comment by jsnanigans** [comment]
@calebeby you have a good point, the only reason its there is for the tests, so It should be enough for it to be in the devDependencies.
A PR would be very welcome, thanks.
