### ISSUE TITLE
Multiple paths 

### ISSUE THREAD

**Issue by stefanomonteiro** [FullHuman/purgecss-webpack-plugin#42]
I am getting an error when setting more than one directory as a `path` using `glob.sync`.

```
new PurgecssPlugin({
      paths: glob.sync(
        "*.php",
        "./templates/*.php",
        "./templates/submit_templates/*.php"
      )
    })
```

```
TypeError: callback provided to sync glob
```

If I config with one of the paths only it works well.

```
new PurgecssPlugin({
      paths: glob.sync("*.php")
    })
```

I have seen a similar example [here](https://roots.io/guides/removing-unused-css-with-purgecss-uncss-in-sage/).

**Comment by shunty-gh** [comment]
In that example you link to the the paths are in an array. You've missed that bit.

    glob.sync([
        ...
    ])

**Comment by jsnanigans** [comment]
I added a example in the readme for glob-all, thanks for reporting this.
https://github.com/FullHuman/purgecss-webpack-plugin#multiple-paths
