### ISSUE TITLE
smilier class names extracting bug

### ISSUE THREAD

**Issue by ctf0** [FullHuman/purgecss-webpack-plugin#44]
am not sure if this is a bug or an issue with the extractor, so here is what i currently have

- config
```js
{
        paths: () => glob.sync([
            path.join(__dirname, 'resources/views/**/*'),
            path.join(__dirname, 'resources/assets/js/**/*')
        ], {nodir: true}),
        extractors: [
            {
                extractor: class {
                    static extract(content) {
                        return content.match(/[\w-:/]+/g) || []
                    }
                },
                extensions: ['html', 'js', 'jsx', 'ts', 'tsx', 'php', 'vue']
            }
        ],
        whitelistPatterns: [/^mce/, /^choices/],
        keyframes: true,
        fontFace: true,
        rejected: true
    }
```

- markup
```html
<span class="tag is-delete"></span>
```

- result
```css
// extracted
.tag:not(body) .delete {
  ...
}

// not extracted
.tag:not(body).is-delete {
  ...
}
```

**Comment by jsnanigans** [comment]
purgecss cannot detect pseudo classes like :not(..)
this is kind of by design to keep performance high, if you need this I would recommend checking out the alternatives here: https://www.purgecss.com/comparison in my opinion UnCSS would be your best option, but performance will suffer a bit and it only works with html

**Comment by ctf0** [comment]
but why one class gets extracted but not the other ?

**Comment by jsnanigans** [comment]
if you take your custom extractor and apply it to:
```html
<span class="tag is-delete"></span>
```
then you get this array of strings: `span`, `class`, `tag`, `is-delete`, `/span`
so 
```css
.tag:not(body) .delete {
  ...
}
```
gets removed because `.deleted` is not in the array.
and 
```css
.tag:not(body).is-delete {
  ...
}
```
is not extracted because `.is-delete` is in the array
