### ISSUE TITLE
What exactly is the "paths" option in this plugin?

### ISSUE THREAD

**Issue by pxwee5** [FullHuman/purgecss-webpack-plugin#8]
```
    new PurgecssPlugin({
      paths: glob.sync(`${PATHS.src}/*`)
    })
```
Not so much an issue, but what exactly does the `paths` option do in this plugin? `paths` is not a PurgeCSS option. It is a purgecss-webpack-plugin option but wasn't mentioned in the README. Some explanation would be great :)

**Comment by Ffloriel** [comment]
Thanks for reporting this. I realize that the readme of the plugin is lacking informations.
`paths` is the `content` of [purgecss](https://www.purgecss.com/configuration.html#content) but requires to use `glob.sync()`.

**Comment by Ffloriel** [comment]
I added a section on the readme and on the [documentation website](https://www.purgecss.com/with-webpack.html)
